import Foundation
import XCTest
@testable import HerdrKit

final class AgentTitleTests: XCTestCase {
    func testCursorConversationTitleWinsOverAutoGeneratedName() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "cursor", "name": "cursor-4d02",
              "agent_status": "working", "workspace_id": "w3", "tab_id": "w3:tP",
              "pane_id": "w3:pP", "focused": false, "revision": 2,
              "cwd": "/Users/jackie_m",
              "terminal_title": "Agent Rename Sync",
              "terminal_title_stripped": "Agent Rename Sync"
            }
            """)
        XCTAssertEqual(agent.title, "Agent Rename Sync")
    }

    func testCustomHerdrNameWinsOverConversationTitle() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "cursor", "name": "门禁修复",
              "agent_status": "done", "workspace_id": "w1", "tab_id": "w1:t8",
              "pane_id": "w1:p8", "focused": false, "revision": 3,
              "cwd": "/tmp/project",
              "terminal_title_stripped": "治理门禁增加"
            }
            """)
        XCTAssertEqual(agent.title, "门禁修复")
    }

    func testAgyWithNoTerminalTitleUsesHerdrName() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "agy", "name": "agy-da7c",
              "agent_status": "done", "workspace_id": "w2", "tab_id": "w2:t7",
              "pane_id": "w2:p7", "focused": false, "revision": 0,
              "cwd": "/tmp/audit-workbench"
            }
            """)
        XCTAssertEqual(agent.title, "agy-da7c")
    }

    func testAgyFallsBackToKindWhenNameMissing() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "agy",
              "agent_status": "done", "workspace_id": "w2", "tab_id": "w2:t7",
              "pane_id": "w2:p7", "focused": false, "revision": 0
            }
            """)
        XCTAssertEqual(agent.title, "agy")
    }

    func testCodexFolderOscTitleIsIgnoredInFavorOfName() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "codex", "name": "codex-e23f",
              "agent_status": "done", "workspace_id": "w4", "tab_id": "w4:t8",
              "pane_id": "w4:p8", "focused": false, "revision": 70,
              "cwd": "/Users/me/50_世联达物流青岛项目（自动化差异核对）",
              "terminal_title": "50_世联达物流青岛项目（自动化差异核对）",
              "terminal_title_stripped": "50_世联达物流青岛项目（自动化差异核对）"
            }
            """)
        XCTAssertEqual(agent.title, "codex-e23f")
    }

    func testTruncatedCwdOscTitleIsGeneric() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "codex", "name": "codex_yesterday",
              "agent_status": "done", "workspace_id": "w3", "tab_id": "w3:t3",
              "pane_id": "w3:p3", "focused": false, "revision": 1,
              "cwd": "/Users/me/47_audit-workbench_审计分析工作台",
              "terminal_title_stripped": "47_audit-workbench_审计..."
            }
            """)
        XCTAssertEqual(agent.title, "codex_yesterday")
    }

    func testOpenCodeConversationTitleIsKept() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "opencode", "name": "opencode-1008",
              "agent_status": "done", "workspace_id": "w3", "tab_id": "w3:tH",
              "pane_id": "w3:pH", "focused": false, "revision": 2,
              "cwd": "/Users/jackie_m",
              "terminal_title_stripped": "OC | herdrm 无法拖动图片到对话框"
            }
            """)
        XCTAssertEqual(agent.title, "OC | herdrm 无法拖动图片到对话框")
    }

    func testKindMatchingOscTitleIsGeneric() {
        XCTAssertTrue(AgentInfo.isGenericTerminalTitle("OpenCode", agentKind: "opencode", cwd: "/tmp"))
        XCTAssertTrue(AgentInfo.isGenericTerminalTitle("agy", agentKind: "agy", cwd: nil))
        XCTAssertFalse(AgentInfo.isGenericTerminalTitle("治理门禁增加", agentKind: "cursor", cwd: "/tmp"))
    }

    func testAutoGeneratedNames() {
        XCTAssertTrue(AgentInfo.isAutoGeneratedName("cursor", agentKind: "cursor"))
        XCTAssertTrue(AgentInfo.isAutoGeneratedName("cursor-4d02", agentKind: "cursor"))
        XCTAssertTrue(AgentInfo.isAutoGeneratedName("codex-e23f", agentKind: "codex"))
        XCTAssertFalse(AgentInfo.isAutoGeneratedName("codex_yesterday", agentKind: "codex"))
        XCTAssertFalse(AgentInfo.isAutoGeneratedName("门禁修复", agentKind: "cursor"))
    }

    func testWireTitleFieldOverridesOscAndName() throws {
        let agent = try decode("""
            {
              "terminal_id": "t", "agent": "codex", "name": "codex-e23f",
              "title": "核对差异",
              "agent_status": "idle", "workspace_id": "w1", "tab_id": "w1:t1",
              "pane_id": "w1:p1", "focused": false, "revision": 0,
              "cwd": "/tmp/project",
              "terminal_title_stripped": "project"
            }
            """)
        XCTAssertEqual(agent.customTitle, "核对差异")
        XCTAssertEqual(agent.title, "核对差异")
    }

    func testSnapshotStillDecodesAgentsWithoutNewFields() throws {
        let data = Data("""
            {"agents":[{
              "terminal_id":"t","agent":"claude","agent_status":"idle",
              "workspace_id":"w1","tab_id":"w1:t1","pane_id":"w1:p1",
              "focused":false,"revision":0
            }],"workspaces":[],"protocol":20,"version":"0.8.2"}
            """.utf8)
        let snapshot = try JSONDecoder().decode(SessionSnapshot.self, from: data)
        XCTAssertEqual(snapshot.agents.first?.title, "claude")
        XCTAssertNil(snapshot.agents.first?.name)
        XCTAssertNil(snapshot.tabs)
    }

    func testChineseTabLabelWinsOverOscAndAutoName() {
        let title = AgentInfo.resolvedTitle(
            customTitle: nil,
            tabLabel: "制度图谱讨论",
            terminalTitle: "32_基于GraphRAG的制度知识图谱建设",
            name: "codex-e23f",
            agentKind: "codex",
            cwd: "/tmp/32_基于GraphRAG的制度知识图谱建设"
        )
        XCTAssertEqual(title, "制度图谱讨论")
    }

    func testGenericTabLabelIsIgnored() {
        XCTAssertTrue(AgentInfo.isGenericTabLabel("agy", agentKind: "agy", name: "agy-da7c"))
        XCTAssertTrue(AgentInfo.isGenericTabLabel("codex", agentKind: "codex", name: "codex-e23f"))
        XCTAssertFalse(AgentInfo.isGenericTabLabel("制度图谱讨论", agentKind: "agy", name: "agy-da7c"))
        let title = AgentInfo.resolvedTitle(
            customTitle: nil,
            tabLabel: "agy",
            terminalTitle: nil,
            name: "agy-da7c",
            agentKind: "agy",
            cwd: "/tmp/project"
        )
        XCTAssertEqual(title, "agy-da7c")
    }

    func testNumericDefaultTabLabelIsNotACustomLabel() {
        // herdr labels fresh tabs with their number; live protocol-20 snapshots
        // show agents in tabs labeled "1". Those must not become the title.
        let fresh = TabInfo(
            tabID: "w1:t1", workspaceID: "w1", number: 1, label: "1",
            focused: true, paneCount: 1, agentStatusRaw: "idle"
        )
        XCTAssertNil(fresh.customLabel)
        let renamed = TabInfo(
            tabID: "w1:t2", workspaceID: "w1", number: 2, label: "制度图谱讨论",
            focused: false, paneCount: 1, agentStatusRaw: nil
        )
        XCTAssertEqual(renamed.customLabel, "制度图谱讨论")
    }

    private func decode(_ json: String) throws -> AgentInfo {
        try JSONDecoder().decode(AgentInfo.self, from: Data(json.utf8))
    }
}
